### ISSUE TITLE
phel library may still require `phel-config.php`

### ISSUE THREAD

**Issue by smeghead** [smeghead/phel-pdo#1]
@Chemaclass 

To confirm the operation of `phel-pdo`, I used `smeghead/phel-old-scool-guestbook` to check.

When I updated `phel-lang` and `phel-pdo`, the following error occurred.

````
Phel\Compiler\Domain\Analyzer\Exceptions\AnalyzerException: Cannot resolve symbol 'pdo/connect'
````
I can't seem to resolve the symbol for phel-pdo.
So, when I created `phel-config.php` in `phel-pdo`, it behaves the same as before.

In the case of a phel application that is the entry point, `phel-config.php` is often unnecessary, but I thought that it might be necessary in the case of a library.
I would like to add `phel-config.php` to `phel-pdo`.

**Comment by Chemaclass** [comment]
Oh, interesting behavior. Maybe this is a feature that we should allow/fix. Probably it's from gacela or phel. I will investigate. But, in the meantime, for sure add it
