### ISSUE TITLE
Should `statement/execute` return result instead of statement object?

### ISSUE THREAD

**Issue by jasalt** [smeghead/phel-pdo#3]
I noted that when inserting something with `statement/execute`, I would expect to receive the insertion result (e.g. `true`) coming from `(php/-> (stmt :stmt) (execute))` which is now discarded with the original statement being returned in https://github.com/phel-lang/phel-pdo/blob/cac6791029ecf7db0abdab5ec5e3cb3d113075a5/src/statement.phel#L48.

This leaves no other way to know if insertion was successful than looking for a `PDOException` if I got it correct. Maybe this could be considered while improving this library. 

Example situation where I noticed this being an issue while making function allowing to insert map into table:

```
  (defn pdo-insert-map  # work in progress function
    [conn table m]
    (let [m-keys (keys m)
          cols (map name m-keys)
          params (str/join ", " m-keys)
          stmt-sql (str "INSERT INTO " table
                        " (" (str/join ", " cols) ") VALUES ("
                        params ")")
          stmt (pdo/prepare pdo-conn stmt-sql)]

      (dofor [[k v] :pairs m]
             (statement/bind-value stmt k v))

      (statement/execute stmt)
      # (php/-> (stmt :stmt) (execute))  # with this instead, true is returned
      ))

  (pdo-insert-map pdo-conn "my_table"
                {:uuid        "testuuid"
                 :create_date "2024-01-01 11:11:11"
                 :order_id    "234"
                 :qty_sold    "5"
                 })
  
  # -> (phel\pdo\statement\statement Printer cannot print this type: PDOStatement)
```

**Comment by jasalt** [comment]
Return value of `(php/-> (stmt :stmt) (execute))` is `true` even if any rows are not affected so my example seems flawed but returning value of `(php/-> (stmt :stmt) (rowCount))` instead seems to be more useful.

That is more inline with other tools too. As example [`wpdb->insert()`](https://developer.wordpress.org/reference/classes/wpdb/insert/) that I'm replacing with PDO in some code as I realize WPDB has other issues (no casting to PHP types while reading, does not throw exceptions on failure as expected, returns error info HTML and other weirdness).

**Comment by jasalt** [comment]
Needs some thinking as `statement->rowCount()` would make more sense in the example code sense (https://github.com/phel-lang/phel-pdo/issues/4#issuecomment-2550473925).. 

Maybe it would be better to keep current `statement/execute` behavior as is and to just figure out / document more usage patterns around it. I'm more familiar to JDBC use with Clojure but new to PDO so still discovering how it works in general.

**Comment by smeghead** [comment]
Thank you very much.

Indeed, as a simple PDO wrapper library, it might be more appropriate for `statement/execute` to return a bool value.

However, the `pho/connect` function explicitly specifies `PDO::ERRMODE_EXCEPTION`, so an exception should be thrown in case of failure.

https://github.com/phel-lang/phel-pdo/blob/cac6791029ecf7db0abdab5ec5e3cb3d113075a5/src/pdo.phel#L21

Therefore, we think it is impossible for the return value of `statement/execute` to be `false`.

Given these considerations, I would like to document that the return value of `statement/execute` is not a bool value without changing the current behavior.
